### ISSUE TITLE
Allow to not include Start Date in Education

### ISSUE THREAD

**Issue by kyawzazaw** [jskherman/imprecv#10]
If I comment out the start date, it gives an error.

This feature is particularly useful if candidates would feel more comfortable not to display the amount of time it took them to graduate or simply thinks this is adding verbosity without additional value

**Comment by jskherman** [comment]
Thanks, I see that could be a problem. I do not have much time around this time of the year since it's the holidays, but I'll take it a look at it once I'm free. For now, as a quick fix, you can override the function for [`#cveducation`](https://github.com/jskherman/cv.typ/blob/932217ca0a3f92daed3d6d74d46cd881134a22f4/cv.typ#L121C1-L145C2) in your [`example.typ` file](https://github.com/jskherman/cv.typ/blob/932217ca0a3f92daed3d6d74d46cd881134a22f4/example.typ#L36C1-L37C25)  to remove the [`#start #sym.dash.en ` portion of line 138 of cv.typ](https://github.com/jskherman/cv.typ/blob/932217ca0a3f92daed3d6d74d46cd881134a22f4/cv.typ#L138C2-L138C41) the function to just be `#end`.

```diff
- #start #sym.dash.en #end
+ #end
```

So for example in your [example.typ on lines 36 and 37](https://github.com/jskherman/cv.typ/blob/932217ca0a3f92daed3d6d74d46cd881134a22f4/example.typ#L37C1-L37C25), you can do:

```typst
// Each section function can be overridden by re-declaring it here
#let cveducation(info, isbreakable: true) = {
    if info.education != none {block[
        == Education
        #for edu in info.education {
            // Parse ISO date strings into datetime objects
            let start = utils.strpdate(edu.startDate)
            let end = utils.strpdate(edu.endDate)
            // Create a block layout for each education entry
            block(width: 100%, breakable: isbreakable)[
                // Line 1: Institution and Location
                #if edu.url != none [
                    *#link(edu.url)[#edu.institution]* #h(1fr) *#edu.location* \
                ] else [
                    *#edu.institution* #h(1fr) *#edu.location* \
                ]
                // Line 2: Degree and Date Range
                #text(style: "italic")[#edu.studyType in #edu.area] #h(1fr)
                #end
                #if edu.honors != none [- *Honors*: #edu.honors.join(", ")]
                #if edu.courses != none [- *Courses*:  #edu.courses.join(", ")]
                #if edu.highlights != none {for hi in edu.highlights [- #eval("[" + hi + "]")]}
            ]
        }
    ]}
}
```

**Comment by jskherman** [comment]
See related PR #15 and implementation in [line 177 of `cv.typ`](https://github.com/jskherman/imprecv/blob/b602e33473677b17f66301a0e7d3e1f579b57c68/cv.typ#L177) that uses [utils.daterange()](https://github.com/jskherman/imprecv/blob/b602e33473677b17f66301a0e7d3e1f579b57c68/utils.typ#L44C1-L54C2) in `utils.typ`.
